{% set version = "1.9.1" %}

package:
    name: pyflann
    version: {{ version }}

source:
    fn: flann-{{ version }}.tar.gz
    url: https://github.com/mariusmuja/flann/archive/{{ version }}.tar.gz
    sha256: b23b5f4e71139faa3bcb39e6bbcc76967fbaf308c4ee9d4f5bfbeceaa76cc5d3
    patches:
        # setup.py: crash with better error if can't find flann install
        - find-path.patch

build:
    number: 1007
    skip: true    # [win and vc<14]

requirements:
    build:
        - {{ compiler("cxx") }}
        - cmake
        - make
    host:
        - python
        - pip
        - setuptools
        - flann {{ version }}
    run:
        - python
        - flann {{ version }}
        - numpy

test:
    imports:
        - pyflann

about:
    home: http://www.cs.ubc.ca/research/flann/
    license: BSD-3-Clause
    license_file: COPYING
    summary: "Python wrapper for FLANN"

extra:
  recipe-maintainers:
    - traversaro
    - jakevdp
    - jakirkham
    - djsutherland
